# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.0'

gem 'sqlite3'

gem 'colorize'

gem 'faraday'
gem 'faraday_middleware'

group :development do
  gem 'debug', '>= 1.0.0'

  gem 'rubocop'

  gem 'rspec'
end
